title: Khaldun Initiative
description: Developing Muslim scholarship in the social sciences and humanities.
sitename: Khaldun Initiative
baseurl: 
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME